name: Latexdiff
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:   # 这里是用来指定哪个文件更改，才会触发的
      - '*.tex'

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: generating diff.tex
        uses: addnab/docker-run-action@v3
        with:
          image: 18810919727/latex_diff:v1
          options: -v ${{ github.workspace }}:/dir:rw
          run: |
            latexdiff /Article/usenix.tex /Article/usenix_new.tex > /Article/diff.tex # 此处可以按需替换 old.tex、new.tex
            echo "Generating diff.tex successfully"
      - name: git add & commit
        run: |
          # 此处可以键入邮箱及姓名
          git config --global user.email "1491657576@qq.com"
          git config --global user.name "zflcs"
          git add .
          git commit -m "update diff"
          git push -u origin main
